name: demo
version: 0.0.1
icon: "airballoon.svg"

inputs:
- name: FLOWCI_DEMO_ENV
  type: string
  required: true

script: |
  echo '#################### DEMO ####################'
  
  echo "hello.plugin.${FLOWCI_DEMO_ENV}"
  
  echo '#################### FINISH ####################'
